server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diploma-pLMS}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none



  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: 9bd14de2fb0bf78d90ef5c33c095e2b7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mailtrap:
  from: Your App <alvoduem@yandex.kz>

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diploma-pLMS}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    locations: classpath:db/migration


gemini:
  api-key: ${GEMINI_API_KEY:}
  api-url: ${GEMINI_API_URL:}




