server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diploma-pLMS}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diploma-pLMS}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    locations: classpath:db/migration


gemini:
  api-key: ${GEMINI_API_KEY:}
  api-url: ${GEMINI_API_URL:}




